UPSTREAM_SOURCE_LABEL="Noto Sans SC"

LOCAL_CACHE_DIR=".cache/upstream"
LOCAL_FONT_FILE=".cache/upstream/NotoSansSC-Regular.otf"

SYMBOL_SOURCE_C="../../src/apps/app_home/src/generated/noto_sans_cjk_12.c"
OUTPUT_C="../../src/apps/app_home/src/generated/noto_sans_cjk_12.c"
OUTPUT_H="../../src/apps/app_home/src/generated/noto_sans_cjk_12.h"
FONT_SYMBOL_NAME="noto_sans_cjk_12"

LV_FONT_SIZE="12"
LV_FONT_BPP="2"
LV_INCLUDE_HEADER="lvgl.h"
