#ifndef APP_HOME_HOME_INTERNAL_H
#define APP_HOME_HOME_INTERNAL_H

#include <stdint.h>

#include "ui_theme.h"

#define HOME_STATUS_BAR_HEIGHT 20
#define HOME_STATUS_BAR_WIDTH 122
#define HOME_STATUS_ICON_GAP 6
#define HOME_STATUS_ICON_SIZE 16
#define HOME_STATUS_ITEM_BOX_SIZE (HOME_STATUS_ICON_SIZE + 4)
#define HOME_STATUS_ACTION_W 34
#define HOME_STATUS_ACTION_BG_COLOR ui_theme_color_hex(UI_THEME_COLOR_SURFACE_ACTIVE)
#define HOME_STATUS_ACTION_TEXT_COLOR ui_theme_color_hex(UI_THEME_COLOR_ACCENT_PRIMARY)
#define HOME_STATUS_BAR_Y 4
#define HOME_TIME_Y 33
#define HOME_DATE_Y 88
#define HOME_WIFI_ONLINE_COLOR ui_theme_color_hex(UI_THEME_COLOR_TEXT_PRIMARY)
#define HOME_WIFI_CONNECTING_COLOR ui_theme_color_hex(UI_THEME_COLOR_STATUS_WARNING)
#define HOME_ICON_MUTED_COLOR ui_theme_color_hex(UI_THEME_COLOR_TEXT_MUTED)
#define HOME_CLAUDE_ACTIVE_COLOR ui_theme_color_hex(UI_THEME_COLOR_TEXT_PRIMARY)
#define HOME_CLAUDE_UNREAD_DOT_COLOR ui_theme_color_hex(UI_THEME_COLOR_ACCENT_PRIMARY)
#define HOME_WIFI_CONNECTING_DOT_COLOR ui_theme_color_hex(UI_THEME_COLOR_STATUS_WARNING)
#define HOME_WEATHER_ROW_HEIGHT 20
#define HOME_WEATHER_ICON_GAP 8
#define HOME_WEATHER_TEXT_COLOR ui_theme_color_hex(UI_THEME_COLOR_TEXT_SECONDARY)
#define HOME_WEATHER_MUTED_COLOR ui_theme_color_hex(UI_THEME_COLOR_TEXT_MUTED)
#define HOME_BG_BASE_COLOR ui_theme_color_hex(UI_THEME_COLOR_CANVAS_BG)
#define HOME_BUBBLE_BG_COLOR ui_theme_color_hex(UI_THEME_COLOR_SURFACE_OVERLAY)
#define HOME_BUBBLE_TEXT_COLOR ui_theme_color_hex(UI_THEME_COLOR_TEXT_PRIMARY)
#define HOME_BUBBLE_MAX_W 220
#define HOME_BUBBLE_PAD_H 6
#define HOME_BUBBLE_PAD_V 4
#define HOME_BUBBLE_RADIUS 8
#define HOME_BUBBLE_FADE_MS 5000
#define HOME_UNREAD_AUTO_CLEAR_MS 5000
#define HOME_SCREENSAVER_IDLE_US (30LL * 60 * 1000000LL)
#define HOME_SCREENSAVER_TIME_COLOR ui_theme_color_hex(UI_THEME_COLOR_TEXT_EMPHASIS)
#define HOME_SCREENSAVER_TIME_LETTER_SPACE 3
#define HOME_SCREENSAVER_FX_W 160
#define HOME_SCREENSAVER_FX_H 43
#define HOME_SCREENSAVER_FX_SCALE 1024U
#define HOME_SCREENSAVER_FX_PERIOD_MS 33
#define HOME_SCREENSAVER_DIRECT_PERIOD_MS 1
#define HOME_TIME_REFRESH_MS 100
#define HOME_SNAPSHOT_REFRESH_MS 500
#define HOME_SCREENSAVER_TASK_STACK_SIZE (6 * 1024)
#define HOME_SCREENSAVER_TASK_PRIORITY 2
#define HOME_SCREENSAVER_TASK_CORE 1
#define HOME_LEFT_HALF_W 280
#define HOME_SPRITE_SCALE 512
#define HOME_SPRITE_X_OFFSET -60
#define HOME_SPRITE_Y_OFFSET 0
#define HOME_SPRITE_MOTION_PERIOD_MS 33

#define APPROVE_BG_COLOR ui_theme_color_hex(UI_THEME_COLOR_SURFACE_OVERLAY)
#define APPROVE_BTN_H 40
#define APPROVE_BTN_GAP 8
#define APPROVE_ALLOW_COLOR ui_theme_color_hex(UI_THEME_COLOR_STATUS_SUCCESS)
#define APPROVE_DENY_COLOR ui_theme_color_hex(UI_THEME_COLOR_STATUS_ERROR)
#define APPROVE_YOLO_COLOR ui_theme_color_hex(UI_THEME_COLOR_STATUS_WARNING)
#define APPROVE_INFO_H 40

#endif
