#ifndef APP_HOME_HOME_INTERNAL_H
#define APP_HOME_HOME_INTERNAL_H

#include <stdint.h>

#define HOME_STATUS_BAR_HEIGHT 20
#define HOME_STATUS_BAR_WIDTH 122
#define HOME_STATUS_ICON_GAP 6
#define HOME_STATUS_ICON_SIZE 16
#define HOME_STATUS_ITEM_BOX_SIZE (HOME_STATUS_ICON_SIZE + 4)
#define HOME_STATUS_ACTION_W 34
#define HOME_STATUS_ACTION_BG_COLOR 0x1e2830
#define HOME_STATUS_ACTION_TEXT_COLOR 0x83d0df
#define HOME_STATUS_BAR_Y 4
#define HOME_TIME_Y 33
#define HOME_DATE_Y 88
#define HOME_WIFI_ONLINE_COLOR 0xffffff
#define HOME_WIFI_CONNECTING_COLOR 0xf3c76d
#define HOME_ICON_MUTED_COLOR 0x5f6b72
#define HOME_CLAUDE_ACTIVE_COLOR 0xffffff
#define HOME_CLAUDE_UNREAD_DOT_COLOR 0xf06c41
#define HOME_WIFI_CONNECTING_DOT_COLOR 0xf3c76d
#define HOME_WEATHER_ROW_HEIGHT 20
#define HOME_WEATHER_ICON_GAP 8
#define HOME_WEATHER_ICON_Y_OFFSET 0
#define HOME_WEATHER_TEXT_Y_OFFSET 3
#define HOME_WEATHER_TEXT_COLOR 0xe3edf2
#define HOME_WEATHER_MUTED_COLOR 0x8da0ab
#define HOME_BG_BASE_COLOR 0x0f1418
#define HOME_BUBBLE_BG_COLOR 0x1e2830
#define HOME_BUBBLE_TEXT_COLOR 0xe3edf2
#define HOME_BUBBLE_MAX_W 220
#define HOME_BUBBLE_PAD_H 6
#define HOME_BUBBLE_PAD_V 4
#define HOME_BUBBLE_RADIUS 8
#define HOME_BUBBLE_FADE_MS 5000
#define HOME_UNREAD_AUTO_CLEAR_MS 5000
#define HOME_SCREENSAVER_IDLE_US (30LL * 60 * 1000000LL)
#define HOME_SCREENSAVER_TIME_COLOR 0xf3f8ff
#define HOME_SCREENSAVER_TIME_LETTER_SPACE 3
#define HOME_SCREENSAVER_FX_W 160
#define HOME_SCREENSAVER_FX_H 43
#define HOME_SCREENSAVER_FX_SCALE 1024U
#define HOME_SCREENSAVER_FX_PERIOD_MS 33
#define HOME_SCREENSAVER_DIRECT_PERIOD_MS 1
#define HOME_TIME_REFRESH_MS 200
#define HOME_SCREENSAVER_TASK_STACK_SIZE (6 * 1024)
#define HOME_SCREENSAVER_TASK_PRIORITY 2
#define HOME_SCREENSAVER_TASK_CORE 1
#define HOME_LEFT_HALF_W 280
#define HOME_SPRITE_SCALE 512

#define APPROVE_BG_COLOR 0x1a2332
#define APPROVE_BTN_H 40
#define APPROVE_BTN_GAP 8
#define APPROVE_ALLOW_COLOR 0x2d8c4e
#define APPROVE_DENY_COLOR 0x8c3030
#define APPROVE_YOLO_COLOR 0x6b5c2e
#define APPROVE_INFO_H 40

#endif
